services:
  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/armckinneygithubio:cached
      - ~/.gitconfig:/root/.gitconfig:ro
      # ai tool persistence
      - ~/.gemini:/root/.gemini:rw
    command: sleep infinity
